import{a as S,S as q,i as s}from"./assets/vendor-DnBR8w-b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const P="49581187-5d65d3ee1f3e1ec6c0e5655f7",$="https://pixabay.com/api/";let d=1;const _=15;let u=0;async function g(r){const t=`${$}?key=${P}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${d}&per_page=${_}`;try{const o=await S.get(t);return u=o.data.totalHits,o.data.hits}catch(o){return console.error("Error fetching images:",o),[]}}function m(r){d=r}function v(){return d}function E(){return u}const y=document.querySelector(".gallery"),H=new q(".gallery a",{captionsData:"alt",captionDelay:250});function f(r){const t=r.map(({webformatURL:o,largeImageURL:i,tags:e,likes:n,views:a,comments:L,downloads:w})=>`
      <li class="gallery__item">
        <a href="${i}">
          <img src="${o}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>❤️ Likes:</b> ${n}</p>
          <p><b>👁 Views:</b> ${a}</p>
          <p><b>💬 Comments:</b> ${L}</p>
          <p><b>⬇️ Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),H.refresh()}function I(){y.innerHTML=""}const O=document.querySelector(".form"),h=document.querySelector(".loader");document.querySelector(".gallery");const l=document.querySelector(".load-more");let c="";O.addEventListener("submit",async r=>{r.preventDefault();const t=r.target.elements.query.value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search query!"});return}c=t,m(1),I(),l.classList.add("hidden"),p();try{const o=await g(c);o.length===0?s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):(f(o),l.classList.toggle("hidden",o.length<15))}catch{s.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{b()}});l.addEventListener("click",async()=>{m(v()+1),p();try{const r=await g(c);f(r);const t=E();document.querySelectorAll(".gallery__item").length>=t&&(l.classList.add("hidden"),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),A()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{b()}});function p(){h.style.display="block"}function b(){h.style.display="none"}function A(){var t;const r=((t=document.querySelector(".gallery__item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
